### ISSUE TITLE
IDK if is a issue

### ISSUE THREAD

**Issue by pirearadu** [linux-sunxi/xf86-video-mali#3]
i recivied this message after i started X.

GET_UMP_SECURE_ID_BUF1 returned 0x1 offset: 0 virt address: 0x4078f000 fb_virt: 0x4078f000
GET_UMP_SECURE_ID_BUF2 returned 0x2 offset: 8294400 virt address: (nil) fb_virt: 0x4078f000
it is normal?

**Comment by rzk** [comment]
Yes, everything seems to be ok.
