### ISSUE TITLE
Symbol miInitializeBackingStore doesn't exists anymore

### ISSUE THREAD

**Issue by cecton** [linux-sunxi/xf86-video-mali#4]
Hello,

This doesn't exist anymore, and apparently hasn't done anything since xserver 1.4.

Regards

  diff --git a/src/mali_fbdev.c b/src/mali_fbdev.c
  index 090cbda..39522d7 100644
  --- a/src/mali_fbdev.c
  +++ b/src/mali_fbdev.c
  @@ -1170,7 +1170,6 @@ static Bool MaliScreenInit(SCREEN_INIT_ARGS_DECL)
                  fPtr->exa = NULL;
          }
-       miInitializeBackingStore(pScreen);
        xf86SetBackingStore(pScreen);
        xf86SetSilkenMouse(pScreen);

**Comment by X-Stranger** [comment]
Looks like miInitializeBackingStore is just deprecated. Try to comment out that call.

**Comment by cecton** [comment]
I know thanks ^_^

I just wanted to say you can remove the line in the repository...

**Comment by cecton** [comment]
Inactive, closing
